# Generated by Django 3.0.4 on 2020-03-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-created'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='services',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(verbose_name='Updated'),
        ),
    ]
