# Generated by Django 3.0.4 on 2020-03-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200323_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
