# Generated by Django 3.0.4 on 2020-03-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
